// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxWuSQcD2wE5Dlp0fKWJmKQEXbtJZTbs',
    appId: '1:990167222735:web:698e37dfaa10a6d872aaba',
    messagingSenderId: '990167222735',
    projectId: 'satsang-5261c',
    authDomain: 'satsang-5261c.firebaseapp.com',
    storageBucket: 'satsang-5261c.appspot.com',
    measurementId: 'G-DKZ6KPNGFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fIp5L2UH6PW3-bTvV9NUYmOF0_9re28',
    appId: '1:990167222735:android:f064bc9231fca54172aaba',
    messagingSenderId: '990167222735',
    projectId: 'satsang-5261c',
    storageBucket: 'satsang-5261c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkKBo3WvEUVkK2AInkjZ0TchVCtKXpzWs',
    appId: '1:990167222735:ios:eab434cf20b9b12f72aaba',
    messagingSenderId: '990167222735',
    projectId: 'satsang-5261c',
    storageBucket: 'satsang-5261c.appspot.com',
    iosClientId: '990167222735-bfa22gsatfg4feie0t53204k29s4dn7m.apps.googleusercontent.com',
    iosBundleId: 'com.satsang.satsang',
  );
}
